__language_name = "English"
"No data input or incorrect input data!!!" = "No data input or incorrect input data!!!"
"Edit Task" = "Edit Task"
connected = "connected"
SettingBlock = "SettingBlock"
variable = "variable"
null = "null"
step = "step"
General = "General"
"window size" = "window size"
variables = "variables"
Send = "Send"
"channel size" = "channel size"
"No correct X input" = "No correct X input"
language = "language"
Clear = "Clear"
"Run All" = "Run All"
address = "address"
Switch = "Switch"
Run = "Run"
HOLD = "HOLD"
"equal step sampling" = "equal step sampling"
"Common Address" = "Common Address"
Script = "Script"
alias = "alias"
text = "text"
Close = "Close"
"path does not exist!!!" = "path does not exist!!!"
"Filter aliases" = "Filter aliases"
interface = "interface"
"identification string" = "identification string"
"data tip" = "data tip"
"Open File" = "Open File"
"log enabled quantities" = "log enabled quantities"
"Auto Search" = "Auto Search"
title = "title"
View = "View"
"saving time" = "saving time"
"font size" = "font size"
"Instrument Registration" = "Instrument Registration"
"confirm delete?" = "confirm delete?"
layout = "layout"
"data processing" = "data processing"
size = "size"
Resistance = "Resistance"
read = "read"
Edit = "Edit"
"Instrument Settings and Status" = "Instrument Settings and Status"
WriteBlock = "WriteBlock"
About = "About"
Instrument = "Instrument"
Disable = "Disable"
Stop = "Stop"
Rename = "Rename"
content = "content"
"data not loaded or data format not supported!" = "data not loaded or data format not supported!"
"Basic Setup" = "Basic Setup"
instrument = "instrument"
"Show Disabled" = "Show Disabled"
"insert above" = "insert above"
"Data Selecting" = "Data Selecting"
pin = "pin"
Console = "Console"
"icon size" = "icon size"
"Task Queue" = "Task Queue"
path = "path"
QueryBlock = "QueryBlock"
font = "font"
Workplace = "Workplace"
"screenshot save" = "screenshot save"
"Instrument CPU Monitor" = "Instrument CPU Monitor"
Plot = "Plot"
Add = "Add"
"Insert Inside" = "Insert Inside"
Logger = "Logger"
Variables = "Variables"
task = "task"
Confirm = "Confirm"
Data = "Data"
buffer = "buffer"
Circuit = "Circuit"
controllers = "controllers"
ReadBlock = "ReadBlock"
Opened = "Opened"
Reboot = "Reboot"
CodeBlock = "CodeBlock"
"Load Project" = "Load Project"
Continue = "Continue"
Interrupt = "Interrupt"
"unit type" = "unit type"
"insert below" = "insert below"
Plots = "Plots"
"real-time data update/manual data update" = "real-time data update/manual data update"
index = "index"
"instrument address" = "instrument address"
Delete = "Delete"
Write = "Write"
Cancel = "Cancel"
command = "command"
status = "status"
"set value" = "set value"
"Refresh instrument list" = "Refresh instrument list"
Refresh = "Refresh"
"display lines" = "display lines"
Reconnect = "Reconnect"
Metrics = "Metrics"
"dual core" = "dual core"
File = "File"
Trilink = "Trilink"
"history command" = "history command"
"data amount per page" = "data amount per page"
Update = "Update"
"Insert Below" = "Insert Below"
"plot type" = "plot type"
Copy = "Copy"
"Edit queue: Task" = "Edit queue: Task"
"select data" = "select data"
"flip vertically" = "flip vertically"
Task = "Task"
Pin = "Pin"
delay = "delay"
"show help" = "show help"
set = "set"
Load = "Load"
output = "output"
"matrix dimension" = "matrix dimension"
Filter = "Filter"
"experimental record" = "experimental record"
"display columns" = "display columns"
SaveBlock = "SaveBlock"
"Add Right" = "Add Right"
ReadingBlock = "ReadingBlock"
"Data Browse" = "Data Browse"
"variable name" = "variable name"
stop = "stop"
"variable type" = "variable type"
offset = "offset"
" Stop " = " Stop "
"Select Data" = "Select Data"
"Manual Input" = "Manual Input"
"Ground End" = "Ground End"
"code header" = "code header"
"Open Folder" = "Open Folder"
"insert inside" = "insert inside"
version = "version"
"Command Test" = "Command Test"
"multi-viewport mode off" = "multi-viewport mode off"
Save = "Save"
Annotation = "Annotation"
enable = "enable"
color = "color"
Query = "Query"
position = "position"
refresh = "refresh"
"file does not exist!!!" = "file does not exist!!!"
"Add Left" = "Add Left"
StrideCodeBlock = "StrideCodeBlock"
clear = "clear"
Pause = "Pause"
"convert to" = "convert to"
"successfully started!" = "successfully started!"
type = "type"
delete = "delete"
"refresh rate" = "refresh rate"
"Convert to" = "Convert to"
"Insert Above" = "Insert Above"
"text editor" = "text editor"
author = "author"
"command type" = "command type"
"Universal Node" = "Universal Node"
"packing size" = "packing size"
New = "New"
input = "input"
running = "running"
Icon = "Icon"
"no workplace selected!!!" = "no workplace selected!!!"
Read = "Read"
mark = "mark"
stopped = "stopped"
" Start " = " Start "
SweepBlock = "SweepBlock"
Help = "Help"
"pickup frame counts" = "pickup frame counts"
"Data Viewer" = "Data Viewer"
"Save Project" = "Save Project"
"flip horizontally" = "flip horizontally"
Select = "Select"
"plot columns" = "plot columns"
Samplebase = "Samplebase"
"fast mode" = "fast mode"
"slow mode" = "slow mode"
"system encodin" = "system encodin"
Unit = "Unit"
"Save Image" = "Save Image"
icon = "icon"
"optional values" = "optional values"
"Data Acquiring" = "Data Acquiring"
sweep = "sweep"
Others = "Others"
Overview = "Overview"
Preferences = "Preferences"
Font = "Font"
number = "number"
Style = "Style"
"sampling rate" = "sampling rate"
rename = "rename"
LogBlock = "LogBlock"
"Confirm delete?" = "Confirm delete?"
Basic = "Basic"
"Search Instruments" = "Search Instruments"
"help document" = "help document"
"unit set" = "unit set"
unit = "unit"
"Instrument Status" = "Instrument Status"
