__language_name = "简体中文"
"No data input or incorrect input data!!!" = "没有数据输入或输入数据有误！！！"
"Edit Task" = "编辑任务"
connected = "已连接"
SettingBlock = "设置模块"
variable = "变量"
null = "空"
step = "步长"
General = "通用"
"window size" = "窗口大小"
variables = "变量"
Send = "发送"
"channel size" = "通道大小"
"No correct X input" = "X输入有误"
"No correct Y input" = "Y输入有误"
language = "语言"
Clear = "清除"
"Run All" = "全部运行"
address = "地址"
Switch = "切换"
Run = "运行"
HOLD = "固定"
"equal step sampling" = "等长采点"
"fixed step sampling" = "定长采点"
"Common Address" = "常用地址"
Script = "脚本"
alias = "别称"
text = "文本"
Close = "关闭"
"path does not exist!!!" = "路径不存在！！！"
"Filter aliases" = "筛选别称"
"Filter variables" = "筛选变量"
interface = "接口"
"identification string" = "身份字符"
"data tip" = "数据提示"
"Open File" = "打开文件"
"log enabled quantities" = "记录启用变量"
"log all quantities" = "记录全部变量"
"Auto Search" = "自动查找"
title = "标题"
View = "查看"
"saving time" = "保存时间"
"font size" = "字体大小"
"Instrument Registration" = "仪器注册"
layout = "布局"
"data processing" = "数据处理"
size = "大小"
Resistance = "电阻"
read = "读取"
Edit = "编辑"
"Instrument Settings and Status" = "仪器设置和状态"
WriteBlock = "写入模块"
About = "关于"
Instrument = "仪器"
Disable = "停用"
Enable = "启用"
Stop = "停止"
Rename = "重命名"
content = "内容"
"data not loaded or data format not supported!" = "数据未加载或数据格式不支持！"
"Basic Setup" = "基本设置"
instrument = "仪器"
"Show Disabled" = "显示停用"
"Hide Disabled" = "隐藏停用"
"Delete Disabled" = "删除停用"
"insert above" = "上方插入"
"Data Selecting" = "数据选择"
pin = "阵脚"
Console = "控制台"
"icon size" = "图标大小"
"Task Queue" = "任务队列"
path = "路径"
QueryBlock = "询问模块"
font = "字体"
Workplace = "工作区"
"screenshot save" = "截图保存"
"Instrument CPU Monitor" = "仪器CPU监测"
Plot = "绘图"
Add = "添加"
"Insert Inside" = "内部插入"
Logger = "日志"
Variables = "变量"
Confirm = "确认"
Data = "数据"
buffer = "缓存"
Circuit = "电路"
controllers = "控制器"
ReadBlock = "读取模块"
Opened = "已打开"
Reboot = "重启"
CodeBlock = "代码模块"
"Load Project" = "加载项目"
Continue = "继续"
Interrupt = "中断"
"unit type" = "单位类型"
"insert below" = "下方插入"
Plots = "绘图"
"real-time data update/manual data update" = "实时数据更新/手动数据更新"
index = "索引"
"instrument address" = "仪器地址"
Delete = "删除"
Write = "写入"
Cancel = "取消"
command = "命令"
status = "状态"
"set value" = "设置值"
"Refresh instrument list" = "刷新仪器列表"
Refresh = "刷新"
"display lines" = "显示行数"
Reconnect = "重连"
Metrics = "监测"
"dual core" = "双核"
"single core" = "单核"
File = "文件"
Trilink = "三通"
"history command" = "历史命令"
"data amount per page" = "单页数据量"
Update = "更新"
"Insert Below" = "下方插入"
"plot type" = "绘图类型"
Copy = "复制"
"Edit queue: Task" = "编辑队列：任务"
"select data" = "选择数据"
"flip vertically" = "上下翻转"
Task = "任务"
Pin = "阵脚"
delay = "延迟"
"show help" = "显示帮助"
set = "设置"
Load = "加载"
output = "输出"
"matrix dimension" = "矩阵维度"
Filter = "筛选"
"experimental record" = "实验记录"
"display columns" = "显示列数"
SaveBlock = "保存模块"
"Add Right" = "向右添加"
ReadingBlock = "读数模块"
"Data Browse" = "数据浏览"
"variable name" = "变量名"
stop = "终点"
"variable type" = "变量类型"
offset = "偏移"
" Stop " = " 结束 "
"Select Data" = "选择数据"
"Manual Input" = "手动输入"
"Ground End" = "接地头"
"code header" = "代码块头"
"Open Folder" = "打开文件夹"
version = "版本"
"Command Test" = "命令测试"
"multi-viewport mode off" = "多视窗模式 关"
"multi-viewport mode on" = "多视窗模式 开"
Save = "保存"
Annotation = "标注"
enable = "启用"
disable = "停用"
color = "颜色"
Query = "询问"
position = "位置"
refresh = "刷新"
"file does not exist!!!" = "文件不存在！！！"
"Add Left" = "向左添加"
StrideCodeBlock = "跨步代码模块"
Pause = "暂停"
"convert to" = "转换为"
"successfully started!" = "启动成功！"
type = "类型"
delete = "删除"
"refresh rate" = "刷新率"
"Convert to" = "转换为"
"Insert Above" = "上方插入"
"text editor" = "文本编辑器"
author = "作者"
"command type" = "命令类型"
"Universal Node" = "通用节点"
"packing size" = "打包尺寸"
New = "新建"
input = "输入"
running = "运行中"
Icon = "图标"
"no workplace selected!!!" = "未选择工作区！！！"
Read = "读取"
mark = "标注"
stopped = "已停止"
" Start " = " 开始 "
SweepBlock = "扫描模块"
Help = "帮助"
"pickup frame counts" = "拾取帧数"
"Data Viewer" = "数据查看"
"Save Project" = "保存项目"
"flip horizontally" = "左右翻转"
Select = "选择"
"plot columns" = "绘图列数"
Samplebase = "样品座"
"fast mode" = "快速模式"
"slow mode" = "慢速模式"
"system encoding" = "系统编码"
Unit = "单位"
"Save Image" = "保存图像"
icon = "图标"
"optional values" = "可选值"
"Data Acquiring" = "数据采集"
sweep = "扫描"
Others = "其它"
Overview = "总览"
Preferences = "首选项"
Font = "字体"
number = "数字"
Style = "风格"
"sampling rate" = "采样率"
LogBlock = "记录模块"
"Confirm delete?" = "确认删除？"
Basic = "基本"
"Search Instruments" = "查找仪器"
"help document" = "帮助文档"
"unit set" = "单位集"
unit = "单位"
"Instrument Status" = "仪器状态"
label = "标签"
"instrument communication failed!!!" = "仪器通讯错误！！！"
"auto searching failed!!!" = "自动查找失败！！！"
"successfully added!" = "添加成功！"
"addition failed!!!" = "添加失败！！！"
"searching instruments" = "正在查找仪器"
"data acqiring, please wait......" = "数据采集中，请稍等。。。"
"unavailable options!" = "不可用的选项！"
"Export" = "导出"
"instrument logging error, program terminates!!!" = "仪器记录错误，程序终止！！！"
BranchBlock = "分支模块"
"interpreting blocks failed!!!" = "模块解释错误！！！"
Interpret = "解释"
"pause!" = "暂停！"
"continue!" = "继续！"
"interrupt!" = "中断！"
"code branch" = "代码分支"
"scale on" = "缩放 开"
"scale off" = "缩放 关"
"nonuniform axes" = "非均匀坐标"
Paste = "粘贴"
"history blocks" = "历史模块"
Undo = "撤销"
Redo = "重做"
"hide window" = "隐藏窗口"