Base.keys(ld::Lockable{T,ReentrantLock}) where T<:AbstractDict = lock(keys, ld)
Base.values(ld::Lockable{T,ReentrantLock}) where T<:AbstractDict = lock(values, ld)
Base.getindex(ld::Lockable{T,ReentrantLock}, k) where T<:AbstractDict = lock(d -> d[k], ld)
Base.setindex!(ld::Lockable{T,ReentrantLock}, v, k) where T<:AbstractDict = lock(d -> d[k] = v, ld)
Base.length(ld::Lockable{T,ReentrantLock}) where T<:AbstractDict = lock(length, ld)
Base.haskey(ld::Lockable{T,ReentrantLock}, k) where T<:AbstractDict = lock(d -> haskey(d, k), ld)
Base.isempty(ld::Lockable{T,ReentrantLock}) where T<:AbstractDict = lock(isempty, ld)
Base.empty!(ld::Lockable{T,ReentrantLock}) where T<:AbstractDict = lock(empty!, ld)
Base.push!(ld::Lockable{T,ReentrantLock}, items...) where T<:AbstractDict = lock(d -> push!(d, items...), ld)
Base.pop!(ld::Lockable{T,ReentrantLock}, k) where T<:AbstractDict = lock(d -> pop!(d, k), ld)