[Bmeasureiv]
cmdheader = "smub.measure.iv()"
U = ""
enable = true
optkeys = []
help = ""
optvalues = []
type = "read"
alias = "B测量电流电压"

[Bmeasurerangei]
cmdheader = "smub.measure.rangei"
U = "A"
enable = true
optkeys = []
help = ""
optvalues = []
type = "set"
alias = "B测量电流范围"

[Asourcelimitv]
cmdheader = "smua.source.limitv"
U = "V"
enable = true
optkeys = []
help = ""
optvalues = []
type = "set"
alias = "A输出电压限制"

[Bmeasurerangev]
cmdheader = "smub.measure.rangev"
U = "V"
enable = true
optkeys = []
help = ""
optvalues = []
type = "set"
alias = "B测量电压范围"

[Ameasurerangei]
cmdheader = "smua.measure.rangei"
U = "A"
enable = true
optkeys = []
help = ""
optvalues = []
type = "set"
alias = "A测量电流范围"

[Ameasureiv]
cmdheader = "smua.measure.iv()"
U = ""
enable = true
optkeys = []
help = ""
optvalues = []
type = "read"
alias = "A测量电流电压"

[Asourcerangev]
cmdheader = "smua.source.rangev"
U = "V"
enable = true
optkeys = []
help = ""
optvalues = []
type = "set"
alias = "A输出电压范围"

[Ameasurev]
cmdheader = "smua.measure.v()"
U = "V"
enable = false
optkeys = []
help = ""
optvalues = []
type = "read"
alias = "A测量电压"

[Bsourcefunc]
cmdheader = "smub.source.func"
U = ""
enable = true
optkeys = ["AMP", "VOLT"]
help = ""
optvalues = ["0.00000e+00", "1.00000e+00"]
type = "set"
alias = "B输出模式"

[Bmeasurev]
cmdheader = "smub.measure.v()"
U = "V"
enable = false
optkeys = []
help = ""
optvalues = []
type = "read"
alias = "B测量电压"

[Asourcelimiti]
cmdheader = "smua.source.limiti"
U = "A"
enable = true
optkeys = []
help = ""
optvalues = []
type = "set"
alias = "A输出电流限制"

[Bsourceleveli]
cmdheader = "smub.source.leveli"
U = "A"
enable = true
optkeys = []
help = ""
optvalues = []
type = "sweep"
alias = "B输出电流"

[Bsourcelimitv]
cmdheader = "smub.source.limitv"
U = "V"
enable = true
optkeys = []
help = ""
optvalues = []
type = "set"
alias = "B输出电压限制"

[Bsourcerangev]
cmdheader = "smub.source.rangev"
U = "V"
enable = true
optkeys = []
help = ""
optvalues = []
type = "set"
alias = "B输出电压范围"

[Asourcefunc]
cmdheader = "smua.source.func"
U = ""
enable = true
optkeys = ["AMP", "VOLT"]
help = ""
optvalues = ["0.00000e+00", "1.00000e+00"]
type = "set"
alias = "A输出模式"

[Boutput]
cmdheader = "smub.source.output"
U = ""
enable = true
optkeys = ["ON", "OFF"]
help = ""
optvalues = ["1.00000e+00", "0.00000e+00"]
type = "set"
alias = "B输出"

[Asourcerangei]
cmdheader = "smua.source.rangei"
U = "A"
enable = true
optkeys = []
help = ""
optvalues = []
type = "set"
alias = "A输出电流范围"

[Bsourcelevelv]
cmdheader = "smub.source.levelv"
U = "V"
enable = true
optkeys = []
help = ""
optvalues = []
type = "sweep"
alias = "B输出电压"

[Ameasurei]
cmdheader = "smua.measure.i()"
U = "A"
enable = false
optkeys = []
help = ""
optvalues = []
type = "read"
alias = "A测量电流"

[Aoutput]
cmdheader = "smua.source.output"
U = ""
enable = true
optkeys = ["ON", "OFF"]
help = ""
optvalues = ["1.00000e+00", "0.00000e+00"]
type = "set"
alias = "A输出"

[Bmeasurei]
cmdheader = "smub.measure.i()"
U = "A"
enable = false
optkeys = []
help = ""
optvalues = []
type = "read"
alias = "B测量电流"

[Ameasurerangev]
cmdheader = "smua.measure.rangev"
U = "V"
enable = true
optkeys = []
help = ""
optvalues = []
type = "set"
alias = "A测量电压范围"

[Bsourcelimiti]
cmdheader = "smub.source.limiti"
U = "A"
enable = true
optkeys = []
help = ""
optvalues = []
type = "set"
alias = "B输出电流限制"

[Bsourcerangei]
cmdheader = "smub.source.rangei"
U = "A"
enable = true
optkeys = []
help = ""
optvalues = []
type = "set"
alias = "B输出电流范围"

[Asourceleveli]
cmdheader = "smua.source.leveli"
U = "A"
enable = true
optkeys = []
help = ""
optvalues = []
type = "sweep"
alias = "A输出电流"

[conf]
idn = "Model 2612"
output_labels = ["AH", "AHS", "BH", "BHS"]
icon = ""
input_labels = ["AL", "ALS", "BL", "BLS"]
cmdtype = "tsp"

[Asourcelevelv]
cmdheader = "smua.source.levelv"
U = "V"
enable = true
optkeys = []
help = ""
optvalues = []
type = "sweep"
alias = "A输出电压"
