[sigactny]
cmdheader = ""
U = ""
enable = true
optkeys = ["HOLD", "RTOS", "RTOZ", "CLMP"]
help = "HOLD:RTOS:RTOZ:CLMP      Ramp status (Hold, to set, to zero, clamp)"
optvalues = ["HOLD", "RTOS", "RTOZ", "CLMP"]
type = "set"
alias = "Y状态"

[sigfldy]
cmdheader = ""
U = "T"
enable = false
optkeys = []
help = ""
optvalues = []
type = "read"
alias = "Y当前场"

[sigrfstz]
cmdheader = ""
U = "T/min"
enable = true
optkeys = []
help = ""
optvalues = []
type = "sweep"
alias = "Z扫描速率"

[sigfsetx]
cmdheader = ""
U = "T"
enable = true
optkeys = []
help = ""
optvalues = []
type = "sweep"
alias = "X目标场"

[sigfldx]
cmdheader = ""
U = "T"
enable = false
optkeys = []
help = ""
optvalues = []
type = "read"
alias = "X当前场"

[sigrfsty]
cmdheader = ""
U = "T/min"
enable = true
optkeys = []
help = ""
optvalues = []
type = "sweep"
alias = "Y扫描速率"

[sigactnx]
cmdheader = ""
U = ""
enable = true
optkeys = ["HOLD", "RTOS", "RTOZ", "CLMP"]
help = "HOLD:RTOS:RTOZ:CLMP      Ramp status (Hold, to set, to zero, clamp)"
optvalues = ["HOLD", "RTOS", "RTOZ", "CLMP"]
type = "set"
alias = "X状态"

[sigpfldy]
cmdheader = ""
U = "T"
enable = true
optkeys = []
help = ""
optvalues = []
type = "read"
alias = "Y当前恒定场"

[sigfsetz]
cmdheader = ""
U = "T"
enable = true
optkeys = []
help = ""
optvalues = []
type = "sweep"
alias = "Z目标场"

[sigrfstx]
cmdheader = ""
U = "T/min"
enable = true
optkeys = []
help = ""
optvalues = []
type = "sweep"
alias = "X扫描速率"

[sigpfldz]
cmdheader = ""
U = "T"
enable = true
optkeys = []
help = ""
optvalues = []
type = "read"
alias = "Z当前恒定场"

[sigpfldx]
cmdheader = ""
U = "T"
enable = true
optkeys = []
help = ""
optvalues = []
type = "read"
alias = "X当前恒定场"

[sigfldz]
cmdheader = ""
U = "T"
enable = false
optkeys = []
help = ""
optvalues = []
type = "read"
alias = "Z当前场"

[sigactnz]
cmdheader = ""
U = ""
enable = true
optkeys = ["HOLD", "RTOS", "RTOZ", "CLMP"]
help = "HOLD:RTOS:RTOZ:CLMP      Ramp status (Hold, to set, to zero, clamp)"
optvalues = ["HOLD", "RTOS", "RTOZ", "CLMP"]
type = "set"
alias = "Z状态"

[conf]
idn = "MERCURY IPS"
output_labels = ["X -", "Y -", "Z -"]
icon = ""
input_labels = ["X +", "Y +", "Z +"]
cmdtype = "scpi"

[sigfsety]
cmdheader = ""
U = "T"
enable = true
optkeys = []
help = ""
optvalues = []
type = "sweep"
alias = "Y目标场"
