[U]
"T/min" = ["T minute^-1"]
A = ["A", "mA", "μA", "nA"]
T = ["T", "mT", "Gauss"]
dBm = ["dBm"]
V = ["V", "mV", "μV", "nV"]
"" = [""]
K = ["K", "mK"]
s = ["s", "minute", "hr", "d"]
Hz = ["Hz", "kHz", "MHz", "GHz"]

[Init]
isremote = true
viewportenable = true
windowsize = [1280, 720]
encoding = "GBK"
editor = "code.cmd"

[DAQ]
savetime = 60
channel_size = 512
packsize = 6
plotshowcol = 4

[InsBuf]
showhelp = true
showcol = 4
refreshrate = 1.0

[Fonts]
dir = "Assets\\Fonts"
size = 18
first = "ZaoZiGongFangShangHeiG0v1ChangGuiTi-1.otf"
second = "arial.ttf"

[Icons]
size = 18

[Logs]
dir = "Assets\\Logs"
refreshrate = 1
showlogline = 100

[BGImage]
path = "Assets\\Necessity/defaultwallpaper.bmp"

[ComAddr]
addrs = ["TCPIP::192.168.31.239::33576::SOCKET"]

[Style]
dir = "Assets\\Styles"
default = "Walkr"
