[U]
"T/min" = ["T minute^-1"]
A = ["A", "mA", "μA", "nA"]
T = ["T", "mT", "Gauss"]
dBm = ["dBm"]
"°" = ["°", "rad"]
V = ["V", "mV", "μV", "nV"]
"" = [""]
K = ["K", "mK"]
s = ["s", "minute", "hr", "d", "ms", "μs"]
Hz = ["Hz", "kHz", "MHz", "GHz"]

[Basic]
isremote = true
viewportenable = false
windowsize = [1280, 720]
encoding = "GBK"
editor = "code.cmd"

[DAQ]
saveimg = false
logall = false
equalstep = false
savetime = 60
channel_size = 512
packsize = 6
plotshowcol = 2
pick_fps = [3, 36]

[InsBuf]
showhelp = false
showcol = 3
refreshrate = 60.0

[Fonts]
dir = "Assets\\Fonts"
size = 18
first = "ZaoZiGongFangShangHeiG0v1ChangGuiTi-1.otf"
second = "arial.ttf"

[Icons]
size = 18

[Console]
dir = "C:\\Users\\q02\\Desktop\\QInsControl.jl\\src\\../Assets\\IOs"
refreshrate = 60.0
showioline = 100
historylen = 100

[Logs]
dir = "Assets\\Logs"
refreshrate = 60.0
showlogline = 600

[BGImage]
path = "Assets\\Necessity/defaultwallpaper.bmp"

[ComAddr]
addrs = ["TCPIP::192.168.31.237::33576::SOCKET", "TCPIP::192.168.1.116::33576::SOCKET"]

[Style]
dir = "C:\\Users\\q02\\Desktop\\QInsControl.jl\\src\\../Assets\\Styles"
default = "WarmWinter"
