[Basic]
isremote = true
viewportenable = false
windowsize = [1280, 720]
encoding = "GBK"
editor = "notepad"

[DtViewer]
showdatarow = 10000

[DAQ]
saveimg = false
logall = false
equalstep = true
savetime = 60
channel_size = 512
packsize = 6
plotshowcol = 2
pick_fps = [3, 36]

[InsBuf]
showhelp = false
showcol = 3
refreshrate = 60.0

[Fonts]
dir = "C:\\Users\\22112\\OneDrive - mails.ucas.ac.cn\\文档\\CODE\\Julia\\MyPackages\\QInsControl.jl\\src\\../Assets\\Fonts"
size = 24
first = "ZaoZiGongFangShangHeiG0v1ChangGuiTi-1.otf"
second = "arial.ttf"

[Icons]
size = 18

[Console]
dir = "C:\\Users\\22112\\OneDrive - mails.ucas.ac.cn\\文档\\CODE\\Julia\\MyPackages\\QInsControl.jl\\src\\../Assets\\IOs"
refreshrate = 60.0
showioline = 100
historylen = 100

[Logs]
dir = "C:\\Users\\22112\\OneDrive - mails.ucas.ac.cn\\文档\\CODE\\Julia\\MyPackages\\QInsControl.jl\\src\\../Assets\\Logs"
refreshrate = 60.0
showlogline = 600

[BGImage]
path = "C:\\Users\\22112\\OneDrive - mails.ucas.ac.cn\\文档\\CODE\\Julia\\MyPackages\\QInsControl.jl\\src\\../Assets\\Necessity/defaultwallpaper.bmp"

[ComAddr]
addrs = []

[Style]
dir = "C:\\Users\\22112\\OneDrive - mails.ucas.ac.cn\\文档\\CODE\\Julia\\MyPackages\\QInsControl.jl\\src\\../Assets\\Styles"
default = "Walkr"

[U]
"T/min" = ["T minute^-1"]
A = ["A", "mA", "μA", "nA"]
T = ["T", "mT", "Gauss"]
dBm = ["dBm"]
"°" = ["°", "rad"]
V = ["V", "mV", "μV", "nV"]
"" = [""]
K = ["K", "mK"]
s = ["s", "minute", "hr", "d", "ms", "μs"]
Hz = ["Hz", "kHz", "MHz", "GHz"]
